### PR TITLE
feat: add new landing page with currently static "whats new" information

### PR DESCRIPTION
**Pull request by ChasNelson1990**
## Description

This is essentially a v0 of a landing page in BAHIS-serve.

Currently it has a static version number and "What's new" section and the "Quick Links" are just the sidebar top-level menu options. It is far from perfect.

relates road86/project-bahis#204

## Database Changes

We need to manually edit the database for this change to work. Essentially open the usermodule_menuitem table and edit the record that is currently for the Form Designer and change it with the following:

```sql
UPDATE core.usermodule_menuitem
SET title='Survey Summary', url='/survey_summary/', list_class='top-level-menu__item', icon_class='fa fa-briefcase', parent_menu_id=NULL, sort_order=0
WHERE id=(SELECT id FROM core.usermodule_menuitem WHERE title='Form Designer');
```

## Checklist

- [x] I have read the road86 Contribution Guide.
- [x] I have checked all commit message styles match the requested structure.
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have assigned at least one reviewer.
- [x] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [x] New database changes have been committed.

### CODE REVIEW

**Comment by shaarful** [comment]
@ChasNelson1990 can not see the button for going to survey summary.

**Comment by ChasNelson1990** [comment]
> @ChasNelson1990 can not see the button for going to survey summary.

See the bit in the description about editing your db

**Comment by shaarful** [comment]
> > @ChasNelson1990 can not see the button for going to survey summary.
> 
> See the bit in the description about editing your db



> > @ChasNelson1990 can not see the button for going to survey summary.
> 
> See the bit in the description about editing your db

sorry, I skipped that part. Now it is okay.

**Review by shaarful — APPROVED** [review]
Looks awesome, a faster index page.

**Pull request merged**
